[project]
name = "mlg-norm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
    "edsnlp[ml]",
    "polars>=1.40.1",
]

[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[tool.ruff]
fix = true
extend-exclude = [
    ".git",
    "__pycache__",
    "__init__.py",
    ".mypy_cache",
    ".pytest_cache",
    ".venv",
    "build",
]
line-length = 100
select = [
    "E",
    "F",
    "W",
    "I001"
]

[tool.setuptools.packages.find]
include = ["mlg_norm*"]

[tool.uv.workspace]
members = [
    "vendor/edsnlp",
]

[tool.uv.sources]
flash-attn = { path = "/export/home/share/datascientists/ia_codage/packages/flash_attn-2.8.3-cp311-cp311-linux_x86_64.whl" }
flash-attn-rpe = { path = "/export/home/share/datascientists/ia_codage/packages/flash_attn_rpe-2.5.9.post17-cp311-cp311-linux_x86_64.whl" }
sparadrap-aphp = { path = "/export/home/share/datascientists/ia_codage/packages/sparadrap_aphp-0.3.6-py3-none-any.whl" }
sparadrap-fr = { path = "/export/home/share/datascientists/ia_codage/packages/sparadrap_fr-0.3.4.post1-py3-none-any.whl" }
confit = { path = "/export/home/pwajsburt/confit" }
dvc = { path = "/export/home/share/datascientists/ia_codage/packages/dvc-3.66.2.dev5+g3c71fdbb0.d20260118-py3-none-any.whl" }
edsnlp = { workspace = true, editable = true }

[dependency-groups]
dev = [
    "flash-attn>=2.8.3",
    "flash-attn-rpe>=2.5.9.post17",
    "ipykernel>=7.2.0",
    "sparadrap-fr==0.3.4.post1",
    "tokenizers>=0.22.3.dev0",
    "xformers==0.0.33.post2",
]
